### ISSUE TITLE
current week returns result, but "past month" returns nothing

### ISSUE THREAD

**Issue by taylorchu** [ClickHouse/metabase-clickhouse-driver#164] opened 2023-05-20 01:43 UTC
### Describe the bug

current week returns result, but "past 1 month" returns nothing.
it seems the result is inconsistent across timestamp filter.

### Steps to reproduce

<img width="358" alt="Screenshot 2023-05-19 at 6 39 41 PM" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/422998/2c30033c-8eee-4a0e-b0e8-3a02339abf30">
<img width="283" alt="Screenshot 2023-05-19 at 6 38 42 PM" src="https://github.com/ClickHouse/metabase-clickhouse-driver/assets/422998/f8f5673e-4eae-415d-aed6-8a2a230fd72b">

1. choose "timestamp" to filter to "this" week. it shows N rows
2. choose "timestamp" to filter last N months including this week shows no rows

### Expected behaviour

filtering by time works.

#### Environment
* metabase-clickhouse-driver version: 1.1.5
* Metabase version: 0.46.3

#### ClickHouse server
* ClickHouse Server version: 23.4

**Comment by taylorchu** [comment] 2023-05-20 01:53
also 
1. current week works but current months return nothing
2. it seems to correlate to time units. 
minute, hour, week work, but day, month, quarter and year do not work.

**Comment by taylorchu** [comment] 2023-05-20 01:57
@slvrtrn could you take a look? it seems like you have a pr, but not sure if it is related.

**Comment by slvrtrn** [comment] 2023-05-22 23:00
@taylorchu, I will have a look once I am back (next week).

**Comment by slvrtrn** [comment] 2023-05-29 16:31
@taylorchu, I checked it with 1.1.6, and it seems to be working as expected.

![image](https://github.com/ClickHouse/metabase-clickhouse-driver/assets/3175289/9228d32c-175e-4181-95f7-6a55abc081cf)

Note that there is an option to include the current month in the result set, and it generates two different queries based on that:

Without "include this month" (May will be excluded):
```
SELECT `default`.`past_test`.`i` AS `i`, `default`.`past_test`.`when` AS `when` 
FROM `default`.`past_test` 
WHERE (`default`.`past_test`.`when` >= toStartOfMonth(toDateTime((CAST(now() AS timestamp) + INTERVAL -1 month))) 
AND `default`.`past_test`.`when` < toStartOfMonth(toDateTime(now()))) 
LIMIT 2000
```

With "include this month" (May will be included):
```
SELECT `default`.`past_test`.`i` AS `i`, `default`.`past_test`.`when` AS `when` 
FROM `default`.`past_test` 
WHERE (`default`.`past_test`.`when` >= toStartOfMonth(toDateTime((CAST(now() AS timestamp) + INTERVAL -1 month))) 
AND `default`.`past_test`.`when` < toStartOfMonth(toDateTime((CAST(now() AS timestamp) + INTERVAL 1 month)))) 
LIMIT 2000
```

^ see the difference in the upper bound

```
`when` < toStartOfMonth(toDateTime(now()))

-- less than the 1st of May
```

vs

```
`when` < toStartOfMonth(toDateTime((CAST(now() AS timestamp) + INTERVAL 1 month)))

-- less than the 1st of June
```

My dataset was defined like the following:

```
CREATE TABLE past_test (i UInt64, when DATETIME) 
ENGINE MergeTree 
ORDER BY i;

INSERT INTO past_test 
SELECT number, now() - toIntervalMinute(randCanonical() * 1000000) 
FROM system.numbers LIMIT 100000;
```

if the issue is still reproducible on your end using 1.1.6, even with "include this month" enabled, can you please share the minimal dataset that can help me investigate this issue?

**Comment by taylorchu** [comment] 2023-05-29 18:58
yes. this is still reproduced in 1.1.6.

My timestamp column is `timestamp DateTime64(3)`.

```
CREATE DATABASE IF NOT EXISTS app;
CREATE TABLE IF NOT EXISTS app.logs
(
  `timestamp` DateTime64(3),
  `host` LowCardinality(String),
  `namespace_name` LowCardinality(String),
  `pod_name` LowCardinality(String),
  `container_name` LowCardinality(String),
  `stream` LowCardinality(String),
  `labels_app` LowCardinality(String),
  `labels_role` LowCardinality(String),
  `message` String
)
ENGINE = MergeTree
PARTITION BY toStartOfHour(timestamp)
ORDER BY (labels_app, pod_name, container_name, timestamp)
TTL toDateTime(timestamp) + INTERVAL 31 DAY;
```

**Comment by slvrtrn** [comment] 2023-05-30 16:01
@taylorchu, after some investigation, it turned out this is due to the issue related to ClickHouse itself: https://github.com/ClickHouse/ClickHouse/issues/50353

There is a workaround available, I will check if it's possible to squeeze it into the `:month` method (that's where the `toStartOfMonth` call is coming from), cause it's the only one for all the Date* types.

**Comment by slvrtrn** [comment] 2023-05-30 19:11
@taylorchu, there is a PR that fixes this odd behavior on the CH server side: https://github.com/ClickHouse/ClickHouse/pull/50280.

**Comment by taylorchu** [comment] 2023-06-01 00:17
Thanks! it seems like a critical bug.

**Comment by taylorchu** [comment] 2023-06-10 01:42
After updating to 23.5, "quarter" and "year" still do not work, but the others do.

**Comment by taylorchu** [comment] 2023-06-12 22:25
Actually that is because I did not include "current quarter and year". This is now fixed.

**Closed** 2023-06-13 20:47 UTC
Labels: bug
